[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "qlminimal"
version = "0.1.0"
description = "QL-bits and their minimal representation"
requires-python = ">=3.9"

dependencies = [
    "matplotlib>=3.9",
    "networkx>=3.2",
    "numpy>=1.24",
    "scipy>=1.10",
]

[tool.setuptools]
packages = ["core"]
