"""
contraction.py
---------------------------------------------
The Cartesian product G = G¹ □ ... □ G^N grows exponentially with the number of
QL-bits.  An equitable partition that groups nodes by their subgraph membership
within each constituent QL-bit yields a quotient (divisor) matrix whose
eigenvalues include all 2^N emergent eigenvalues of the full product while
discarding the bulk incoherent states.

Divisor matrix structure
------------------------
For N QL-bits with parameters (k_q, l_q):
  Q = (Σ k_q) · I_{2^N}  +  Σ_q  l_q · (I_{2^(N-1-q)} ⊗ σ_x ⊗ I_{2^q})

where σ_x = [[0,1],[1,0]].

The diagonal term (Σ k_q)·I arises from within-cell connectivity (self-loops
in the quotient). Removing it shifts every emergent eigenvalue by -Σ k_q.

The emergent eigenvalues of the quotient are all 2^N combinations
  λ = (Σ k_q) ± l_1 ± l_2 ± ... ± l_N

matching the sums of single-QL-bit emergent eigenvalues k_q ± l_q.

Two computation paths are provided:

  minimal_quotient — builds the 2^N × 2^N divisor matrix *directly* from
      (k, l) parameters without forming the full Cartesian product matrix.
      Efficient for any N; the preferred construction for large systems.

  contract_ql_bit — given the full coupled matrix from couple_ql_bits(),
      collapses a single QL-bit (specified by index) to its 2-node quotient
      via the characteristic matrix formula Aπ = (1/N_q) · S^T A S.
      Can be called iteratively to reach the full minimal representation.
      Practical up to the sizes where the full matrix can be stored.

Public API
----------
minimal_quotient(*ql_bits)                      -> (matrix, quotient_info)
contract_ql_bit(coupled_result, target)         -> (matrix, updated_info)
"""

import numpy as np


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_SIGMA_X = np.array([[0, 1], [1, 0]], dtype=float)


# ---------------------------------------------------------------------------
# Direct construction — no full Cartesian product required
# ---------------------------------------------------------------------------

def minimal_quotient(*ql_bits):
    """
    Build the minimal 2^N × 2^N divisor matrix directly from QL-bit parameters.

    Does not require the full Cartesian product matrix — uses only (k, l) for
    each QL-bit.  The result is the minimal quotient graph that preserves the
    2^N emergent eigenpairs of the full product (Theorem 1, Horvat et al.).

    Divisor matrix:
      Q = (Σ k_q)·I_{2^N}  +  Σ_q  l_q · (I_{2^(N-1-q)} ⊗ σ_x ⊗ I_{2^q})

    The diagonal (Σ k_q)·I represents self-loops generated by the equitable
    partition.  Removing this term shifts all eigenvalues by -N·k (for uniform
    k), recovering the ±l_q structure centred at zero.

    Parameters
    ----------
    *ql_bits : two or more (np.ndarray, dict) tuples
        Each is the direct output of generate_quantum_like_bit or a prior
        couple_ql_bits call.  Only the info dict is used; the matrix is ignored.

    Returns
    -------
    matrix      : np.ndarray   (2^N × 2^N) divisor matrix
    quotient_info : dict
        num_ql_bits   — N
        total_nodes   — 2^N
        k_values      — list of k per QL-bit
        l_values      — list of l per QL-bit
        diagonal_shift — Σ k_q (the self-loop contribution on the diagonal)
        ql_bits       — flat list of original QL-bit info dicts

    Raises
    ------
    ValueError  If fewer than one QL-bit is provided.
    """
    if len(ql_bits) < 1:
        raise ValueError("minimal_quotient requires at least one QL-bit")

    infos = _flatten_infos(ql_bits)
    N = len(infos)
    dim = 2 ** N

    k_values = [info['k'] for info in infos]
    l_values = [info['l'] for info in infos]

    Q = np.sum(k_values) * np.eye(dim)

    for q, l_q in enumerate(l_values):
        # QL-bit q is at position q in the chain (q=0 is innermost / ql_bits[0]).
        # σ_x lives at bit-position q from the right in the tensor product,
        # i.e., position (N-1-q) from the left.
        left_dim  = 2 ** (N - 1 - q)
        right_dim = 2 ** q
        term = np.kron(np.kron(np.eye(left_dim), _SIGMA_X), np.eye(right_dim))
        Q += l_q * term

    quotient_info = {
        'num_ql_bits':    N,
        'total_nodes':    dim,
        'k_values':       k_values,
        'l_values':       l_values,
        'diagonal_shift': int(np.sum(k_values)),
        'ql_bits':        infos,
        # Every QL-bit is contracted to 1 node per subgraph (2 total).
        # These fields let gate functions use the correct strides/sizes.
        'contracted':      set(range(N)),
        'current_strides': [2 ** q for q in range(N)],
    }

    return Q, quotient_info


# ---------------------------------------------------------------------------
# Iterative contraction — works on the full coupled matrix
# ---------------------------------------------------------------------------

def contract_ql_bit(coupled_result, target):
    """
    Contract a single QL-bit in the full Cartesian product via equitable partition.

    Collapses all N_q nodes in each subgraph of the target QL-bit down to one
    representative node, producing an intermediate quotient matrix whose size is
    (n_total / N_q) × (n_total / N_q), where n_total is the current matrix size
    and N_q is the number of nodes per subgraph in the target QL-bit.

    Uses the characteristic matrix formula:
      Aπ = (1 / N_q) · S^T A S

    where S is the indicator matrix mapping each full-graph node to its cell
    (identified by its subgraph membership in the target QL-bit and its exact
    positions in all other QL-bits).  Because the partition is equitable, every
    cell has exactly N_q nodes and (S^T S)^{-1} = (1/N_q)·I.

    Calling this function iteratively on all QL-bit indices (in any order, by
    Lemma 4) reaches the same 2^N minimal representation as minimal_quotient.

    Parameters
    ----------
    coupled_result : (np.ndarray, dict)
        Output of couple_ql_bits (or a prior call to contract_ql_bit).
    target : int
        0-based index into network_info['ql_bits'] identifying which QL-bit
        to contract.  ql_bits[0] is the innermost (first argument to
        couple_ql_bits); ql_bits[-1] is the outermost.

    Returns
    -------
    matrix       : np.ndarray   Contracted adjacency matrix
    updated_info : dict
        num_ql_bits     — unchanged
        total_nodes     — new (smaller) matrix size
        contracted      — set of ql_bit indices already contracted
        ql_bits         — original flat info list (unchanged)

    Raises
    ------
    ValueError  If target is out of range or already contracted.
    IndexError  If matrix size is inconsistent with ql_bit info.
    """
    matrix, network_info = coupled_result

    infos = network_info['ql_bits']
    N = len(infos)

    if not (0 <= target < N):
        raise ValueError(f"target {target} is out of range for {N} QL-bits")

    already_contracted = network_info.get('contracted', set())
    if target in already_contracted:
        raise ValueError(f"QL-bit {target} has already been contracted")

    # --- Determine effective sizes (contracted QL-bits occupy 2 nodes) ------
    eff_sizes = [
        2 if q in already_contracted else infos[q]['total_nodes']
        for q in range(N)
    ]

    n_total = matrix.shape[0]
    expected = 1
    for s in eff_sizes:
        expected *= s
    if n_total != expected:
        raise IndexError(
            f"Matrix size {n_total} does not match expected product of QL-bit "
            f"sizes {eff_sizes} = {expected}"
        )

    # --- Strides in the CURRENT matrix (must be tracked across contractions) -
    # After each contraction the node layout changes, so we cannot re-derive
    # strides from eff_sizes alone.  We store them in the info dict and update
    # after every call.
    #
    # Stride update rule when contracting target with size n_t and stride_t:
    #   q < target  →  new_stride[q] = stride[q] * 2
    #   q = target  →  new_stride[q] = 1   (s_t becomes the new LSB)
    #   q > target  →  new_stride[q] = stride[q] // n_t * 2
    if 'current_strides' in network_info:
        current_strides = list(network_info['current_strides'])
    else:
        # First contraction: strides are derived from the original full sizes
        full_sizes = [info['total_nodes'] for info in infos]
        current_strides = _compute_strides(full_sizes)

    stride_t      = current_strides[target]
    n_t           = eff_sizes[target]          # full size of target in current matrix
    eff_half_t    = infos[target]['N']         # nodes per subgraph (always original N_q)

    # --- Assign each node to a cell -----------------------------------------
    # Cell index = other_idx * 2 + s_t, where:
    #   s_t ∈ {0,1} is the subgraph label for the target QL-bit
    #   other_idx encodes the exact position in every other QL-bit
    node_idx  = np.arange(n_total, dtype=np.int64)
    v_t       = (node_idx // stride_t) % n_t
    s_t       = (v_t >= eff_half_t).astype(np.int64)

    lower     = node_idx % stride_t
    upper     = node_idx // (stride_t * n_t)
    other_idx = lower + upper * stride_t

    n_contracted = (n_total // n_t) * 2
    cell_idx     = other_idx * 2 + s_t

    # --- Characteristic matrix S --------------------------------------------
    S = np.zeros((n_total, n_contracted), dtype=float)
    S[node_idx, cell_idx] = 1.0

    # Aπ = (1 / N_q) * S^T A S  (equitable: all cells have size N_q = eff_half_t)
    Aπ = (S.T @ (matrix @ S)) / eff_half_t

    # --- Update strides for the contracted matrix ---------------------------
    new_strides = []
    for q in range(N):
        if q < target:
            new_strides.append(current_strides[q] * 2)
        elif q == target:
            new_strides.append(1)
        else:
            new_strides.append(current_strides[q] // n_t * 2)

    updated_info = {
        'num_ql_bits':    N,
        'total_nodes':    n_contracted,
        'contracted':     already_contracted | {target},
        'current_strides': new_strides,
        'ql_bits':        infos,
    }

    return Aπ, updated_info


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def _flatten_infos(ql_bits):
    """Flatten nested ql_bit info lists from couple_ql_bits output."""
    infos = []
    for item in ql_bits:
        _, info = item
        infos.extend(info.get('ql_bits', [info]))
    return infos


def _compute_strides(sizes):
    """
    Return strides for a row-major multi-index with given dimension sizes.
    sizes[0] is the innermost (fastest-changing) dimension.
    """
    strides = []
    stride = 1
    for s in sizes:
        strides.append(stride)
        stride *= s
    return strides
